### ISSUE TITLE
前端界面显示问题 

### ISSUE THREAD

**Issue by C-wc** [weigp1/stuMS-front#8]
前端界面显示存在以下问题：
1、审核进度界面：当显示的卡片数超过6张（即出现第3行）时，背景图无法完全覆盖，界面底部会出现空白，出现显示bug。
2、综测填报界面：当综测项卡片超过3张时，无显示问题；但当综测项卡片不超过3张时，卡片有部分重叠在一起，出现显示bug。

**Comment by ZhangCWei** [comment]
已解决
